apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment
    kompose.service.type: LoadBalancer
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  containers:
    - image: lukondefmwila/dkr-multicontainer-app-client
      name: client
      ports:
        - containerPort: 3000
      resources: {}
  restartPolicy: OnFailure
status: {}
